"""Initial migration

Revision ID: 4003ac1f23a7
Revises: 
Create Date: 2025-03-15 20:59:33.047050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4003ac1f23a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index('idx_user_roles_role_id')

    op.drop_table('user_roles')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('idx_transactions_order_id')

    op.drop_table('transactions')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('idx_notifications_read')

    op.drop_table('notifications')
    with op.batch_alter_table('stock_prices', schema=None) as batch_op:
        batch_op.drop_index('idx_stock_date')
        batch_op.drop_index('idx_stock_prices_stock_id_date')
        batch_op.drop_index('idx_stock_prices_year')

    op.drop_table('stock_prices')
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_index('symbol')

    op.drop_table('stocks')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index('name')

    op.drop_table('roles')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index('idx_predictions_date')

    op.drop_table('predictions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('idx_users_created_at')
        batch_op.drop_index('idx_users_email')
        batch_op.drop_index('idx_users_updated_at')
        batch_op.drop_index('idx_users_username')
        batch_op.drop_index('username')

    op.drop_table('users')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('idx_orders_stock_id')
        batch_op.drop_index('idx_orders_user_id')

    op.drop_table('orders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stock_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_type', mysql.ENUM('BUY', 'SELL'), nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('status', mysql.ENUM('PENDING', 'COMPLETED', 'CANCELLED'), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('executed_at', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name='orders_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='orders_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('idx_orders_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_orders_stock_id', ['stock_id'], unique=False)

    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=True)
        batch_op.create_index('idx_users_username', ['username'], unique=False)
        batch_op.create_index('idx_users_updated_at', ['updated_at'], unique=False)
        batch_op.create_index('idx_users_email', ['email'], unique=False)
        batch_op.create_index('idx_users_created_at', ['created_at'], unique=False)
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('predictions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stock_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('predicted_price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('prediction_date', mysql.DATETIME(), nullable=False),
    sa.Column('model_used', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name='predictions_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index('idx_predictions_date', ['prediction_date'], unique=False)

    op.create_table('roles',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=True)

    op.create_table('stocks',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('exchange', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.create_index('symbol', ['symbol'], unique=True)

    op.create_table('stock_prices',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stock_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', mysql.DATETIME(), nullable=False),
    sa.Column('year', mysql.INTEGER(), sa.Computed('(year(`date`))', persisted=True), autoincrement=False, nullable=True),
    sa.Column('open_price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('high_price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('low_price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('close_price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('volume', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('stock_prices', schema=None) as batch_op:
        batch_op.create_index('idx_stock_prices_year', ['year'], unique=False)
        batch_op.create_index('idx_stock_prices_stock_id_date', ['stock_id', 'year', 'date'], unique=False)
        batch_op.create_index('idx_stock_date', ['stock_id', 'date'], unique=False)

    op.create_table('notifications',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('is_read', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notifications_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('idx_notifications_read', ['user_id', 'is_read', 'created_at'], unique=False)

    op.create_table('transactions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('executed_price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('executed_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='transactions_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('idx_transactions_order_id', ['order_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='user_roles_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_roles_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index('idx_user_roles_role_id', ['role_id'], unique=False)

    # ### end Alembic commands ###
